dist: trusty
sudo: required
language: node_js

env:
  - V=0.3.2rc3 URL=https://storage.googleapis.com/bazel/0.3.2/rc3/bazel-0.3.2rc3-installer-linux-x86_64.sh FLAGS=''
  - V=0.3.2rc2 URL=https://storage.googleapis.com/bazel/0.3.2/rc2/bazel-0.3.2rc2-installer-linux-x86_64.sh FLAGS=''
  - V=0.3.1 URL=https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel-0.3.1-installer-linux-x86_64.sh FLAGS=''

before_install:
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --sandbox_debug \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,1,1.0 \
      //... \
      $FLAGS
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      run \
      --verbose_failures \
      --sandbox_debug \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,1,1.0 \
      //examples/foo \
      $FLAGS

notifications:
  email: false
